sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install: "make init"
script: "make ci"
cache: "pip"
jobs:
  include:
    - stage: "coverage"
      python: "3.6"
      script: "pipenv run codecov"
